name: Python Release

on:
  push:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  PYPI_TOKEN: ${{ secrets.PYPI_TOKEN_DIST }}
  DIST_DIR: ${{ github.sha }}

jobs:

  create_wheels_manylinux_aarch64:
    runs-on: ubuntu-latest
    name: Create wheels for manylinux2014
    container: quay.io/pypa/manylinux2014_aarch64
    steps:
      - uses: actions/checkout@v1

      - name: Build and audit wheels
        working-directory: ./bindings/python
        run: docker run --rm -v .:/work:rw --workdir=/work quay.io/pypa/manylinux2014_aarch64 bash -exc build-wheels.sh
        
